### ISSUE TITLE
Step settings in channel trigger display not updated from changes ramp & delay overview

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#160] opened 2021-02-11 21:39 UTC
If I go into the trigger menu, select Step and set value (note the 5.2V):

![SetStep1](https://user-images.githubusercontent.com/8796121/107701711-91744d80-6cb9-11eb-9b1b-2a31722428d7.jpg)

Then press 'ramp & delay overview' and in this display change values (e.d. voltage to 5.5):

![SetStep2](https://user-images.githubusercontent.com/8796121/107701797-b072df80-6cb9-11eb-8f76-d84cabd06840.jpg)

IF I then press the OK button, going back to the original trigger menu, the old values are displayed: 

![SetStep3](https://user-images.githubusercontent.com/8796121/107701868-c5e80980-6cb9-11eb-937c-6905d12d4424.jpg)

Leaving the trigger menu and returning to it shows the updated value (5.5V). So I think the display is just not refreshed.

Tested on 1.6-RC

**Comment by prasimix** [comment] 2021-02-12 06:41
I cannot reproduce this issue, perhaps because I'm testing it on 1.6-RC2

**Comment by fietser28** [comment] 2021-02-15 10:50
Just tried it with 1.6-RC2. Problem is still there. How can I explain it more clearly? Upload a movie in Discord?

Basically the values are not updated on the screen 'chx: trigger settings' if you close the 'ramp & delay overview' screen.

**Comment by prasimix** [comment] 2021-02-15 11:56
It should be fixed now in 14cdfee

**Comment by fietser28** [comment] 2021-02-15 21:39
Tested with RC3. It is fixed. Thanks.

**Comment by prasimix** [comment] 2021-02-15 21:40
Fixed

**Closed by prasimix** 2021-02-15 21:40 UTC
Labels: P3-major, bug
